CREATE TABLE tx_gosuits_domain_model_gogame (
	uid int(11) unsigned DEFAULT '0' NOT NULL auto_increment,
	pid int(11) DEFAULT '0' NOT NULL,
	tstamp int(11) DEFAULT '0' NOT NULL,
	crdate int(11) DEFAULT '0' NOT NULL,
	cruser_id int(11) DEFAULT '0' NOT NULL,
	sys_language_uid int(11) DEFAULT '0' NOT NULL,
	l10n_parent int(11) DEFAULT '0' NOT NULL,
	l10n_diffsource mediumtext,
	deleted tinyint(4) DEFAULT '0' NOT NULL,
	hidden tinyint(4) DEFAULT '0' NOT NULL,
	starttime int(11) DEFAULT '0' NOT NULL,
	endtime int(11) DEFAULT '0' NOT NULL,
	fe_group varchar(100) DEFAULT '0' NOT NULL,
	
	type tinytext DEFAULT '0' NOT NULL,
	title varchar(255) DEFAULT '' NOT NULL,
	white tinytext DEFAULT 'WHITE' NOT NULL,
	black tinytext DEFAULT 'BLACK' NOT NULL,
	playdate int(11) DEFAULT '0' NOT NULL,
	sgftext text,
	sgffile text,

	PRIMARY KEY (uid),
	KEY parent (pid),
);
